git:
  depth: 1
  quiet: true

branches:
  only:
    - master

language: python

python: 3.7

addons:
  apt:
    packages:
      - ninja-build

script:
  - pip3 install meson
  - ./meson-gse/meson-gse
  - meson build
  - ninja -C build test install extension.zip

matrix:
  include:
    - os: linux
      dist: xenial
